### ISSUE TITLE
go-lustre is distributed under MIT license whereas liblustreapi is still under GPL 

### ISSUE THREAD

**Issue by barzoj** [intel-hpdd/go-lustre#1]
https://jira.hpdd.intel.com/browse/LU-5969 isn't resolved yet

**Comment by mjmac** [comment]
Hi Dennis.

The MIT license is [compatible](https://www.gnu.org/licenses/gpl-faq.en.html#WhatDoesCompatMean) with the GPL. Any distributed binaries which result from combining go-lustre and liblustreapi will be covered by the same version of the GPL as that which covers liblustreapi.

Do you have specific concerns about this issue?

**Comment by barzoj** [comment]
Hi Michael, 

I may be probably wrong, however my understanding is that if GPLed code is included in your project, even via linking, you must provide your project under GPL 

Again, I just wanted to point it out - feel free to ignore me and close the issue if you are 100% sure

**Comment by mjmac** [comment]
Hi Dennis.

Thanks for the input. Software licensing can be kind of confusing and tricky. The thing about the GPL is that it is a distribution license, so it only comes into effect when binaries are distributed outside of an organization. The original intent of the GPL was to ensure that users of software covered by the GPL would always be able to get the source code for the software.

In our case, the go-lustre code is covered by the MIT license (also known as the [Expat License](https://www.gnu.org/licenses/license-list.en.html#Expat)) which is more permissive than the GPL. As such, it is compatible with the GPL when combined into a binary and distributed. If the binary is not distributed, then the GPL doesn't even come into play at all.
